create table if not exists mpa_ratings(
    id integer generated by default as identity primary key,
    name varchar(64)
);

create table if not exists films (
    id integer generated by default as identity primary key,
    name varchar(128),
    description varchar(1024),
    release_date date,
    duration integer,
    mpa_rating_id integer references mpa_ratings(id)
);

create table if not exists genres (
    id integer generated by default as identity primary key,
    name varchar(64)
);

create table if not exists film_genres (
    film_id integer references films(id),
    genre_id integer references genres(id)
);

create table if not exists users (
    id integer generated by default as identity primary key,
    login varchar(64),
    name varchar(64),
    email varchar (64),
    birthday date
);

create table if not exists friends (
    user_id integer references users(id),
    friend_id integer references users(id),
    is_confirmed boolean
);

create table if not exists film_likes (
    film_id integer references films(id),
    user_id integer references users(id)
);